# Generated by Django 4.1.1 on 2022-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
