# Generated by Django 4.1.1 on 2022-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_employees_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='CsvFileName',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
