# Generated by Django 4.1.1 on 2022-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_alter_csvfile_csvfilename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgroundsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundcolorparams', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(max_length=100),
        ),
    ]
