# Generated by Django 4.1.1 on 2022-09-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_backgroundsettings_alter_employees_photofilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('backgroundcolorparamsId', models.AutoField(primary_key=True, serialize=False)),
                ('backgroundcolorparams', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Backgroundsettings',
        ),
    ]
