# Generated by Django 4.1.1 on 2022-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_background_delete_backgroundsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='CsvFileName',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
